name: Wasm-Pack Tests
run-name: ${{ github.actor }} Push Code
on: [pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nanasess/setup-chromedriver@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: cargo test
      - run: wasm-pack test --headless --chrome
      - run: wasm-pack test --headless --firefox

          